### ISSUE TITLE
List Products in Wishlist

### ISSUE THREAD

**Issue by VGmt** [NYU-DevOps-Squad-Wishlists/wishlists#10]
**User Story:**
As a User, I need to see a list of all products stored in my wishlist, so that I can review them if needed

**Assumptions:**
* Create/Update/Delete actions all update the list accordingly

**Acceptance Criteria:**
AC1) It returns no product if there are none currently stored
AC2) It lists all items and its current state reflects all prior modifications made to it

**Comment by biegel** [comment]
This is a duplicate of the `GET wishlists/:id` endpoint, which returns all the items in the wishlist along with the wishlist model information
