### ISSUE TITLE
Add honcho functionality

### ISSUE THREAD

**Issue by ZiyiHuang96** [NYU-DevOps-Squad-Wishlists/wishlists#26]
**User Story:**
As a developer, I need honcho start, so that we can start the service fast

**Assumptions:**
* Vagrantfile is set up
* #42 is completed

**Acceptance Criteria:**
AC1) Service is started when type ```honcho start```
AC2) Make sure command ```honcho``` works the ```Procfile``` added in #42 

**Testing Plan:**
Service is started when type ```honcho start```

**Comment by biegel** [comment]
@ZiyiHuang96 I tested this but I don't think it's working correctly.  Can you check this out?

**Comment by biegel** [comment]
Sorry @ZiyiHuang96 , this is working -- I think I was looking at an old branch.
