### ISSUE TITLE
Create config for nosetests

### ISSUE THREAD

**Issue by biegel** [NYU-DevOps-Squad-Wishlists/wishlists#3]
**User Story:**
As an engineer, I need a config file for my tests so that I can run ```nosetests``` and run all the tests.

**Assumptions:**
* Assumes https://github.com/NYU-DevOps-Squad-Wishlists/wishlists/issues/1 and https://github.com/NYU-DevOps-Squad-Wishlists/wishlists/issues/2 are complete

**Acceptance Criteria:**
AC1) ```setup.cfg``` is committed to the project root
AC2) The config file contains all the test options
AC3) Create a ```.tests/``` folder to contain all the tests

**Documentation:**
* Nosetests documentation: https://nose.readthedocs.io/en/latest/

**Comment by billykern** [comment]
this will be addressed as part of https://github.com/NYU-DevOps-Squad-Wishlists/wishlists/issues/5

**Comment by billykern** [comment]
meant to close a different issue 😬

**Comment by biegel** [comment]
Confirmed
