### ISSUE TITLE
Add Swagger Docs

### ISSUE THREAD

**Issue by ZiyiHuang96** [NYU-DevOps-Squad-Wishlists/wishlists#56]
**User Story:**
As a developer, I need swagger document to rest API, so that we can have a format describing REST APIs.

**Assumptions:**

**Acceptance Criteria:**
AC1) Add Swagger annotations to your service to document your REST API using Flask-RESTX
AC2) The documentation API must be available at: `/apidocs/`
AC3) Add Swagger data models to document your API payloads
AC4) Ensure that you Swagger docs work correctly and specify your data model so that others know what to send to your API 

**Testing Plan:**
Access `/apidocs/` and check each endpoint

**Documentation:**
[swagger](https://swagger.io/)

**Comment by billykern** [comment]
is this issue distinct from other issues like https://github.com/NYU-DevOps-Squad-Wishlists/wishlists/issues/74 ?

**Comment by biegel** [comment]
@billykern yes, at least that's my understanding.  We need to setup and install Swagger before we can actually start adding the automatic documentation to individual REST endpoints in the python code
