### ISSUE TITLE
Create test case for Models

### ISSUE THREAD

**Issue by ZiyiHuang96** [NYU-DevOps-Squad-Wishlists/wishlists#6]
**User Story:**
As an engineer, I need tests for my DB models, so that the db tables are covered by test cases, and engineers can develop code to pass the tests

**Assumptions:**
* Assumes https://github.com/NYU-DevOps-Squad-Wishlists/wishlists/issues/3 and https://github.com/NYU-DevOps-Squad-Wishlists/wishlists/issues/5 are complete

**Acceptance Criteria:**
AC1) Create, Read, Update, Delete should be covered
AC2) After run nosetest, at least 95% code coverage

**Documentation:**
* Nosetests documentation: https://nose.readthedocs.io/en/latest/

**Comment by billykern** [comment]
this will be addressed as part of https://github.com/NYU-DevOps-Squad-Wishlists/wishlists/issues/5
