### ISSUE TITLE
Create test case for route

### ISSUE THREAD

**Issue by ZiyiHuang96** [NYU-DevOps-Squad-Wishlists/wishlists#7]
**User Story:**
As an engineer, I need test cases for routes(service), so that the routes are covered by test cases, and engineers can develop code to pass the tests

**Assumptions:**
* Assumes https://github.com/NYU-DevOps-Squad-Wishlists/wishlists/issues/3 and https://github.com/NYU-DevOps-Squad-Wishlists/wishlists/issues/5 are complete

**Acceptance Criteria:**
AC1) There should be tests for each of Create, Read, Update, Delete, List, Query, Action, traversing both happy paths and sad paths
AC2) Run these tests using nosetest as you develop the code making them all green (passing)
AC3) Use the coverage tool to measure your test coverage. Your goal is get coverage of at least 95%.

**Documentation:**
* Nosetests documentation: https://nose.readthedocs.io/en/latest/

**Comment by billykern** [comment]
test cases will be developed and merged with the feature PRs
